server:
  port: 8005

spring:
  application:
    name: cloud-consul_provider-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname:127.0.0.1
        service-name: ${spring.application.name} #对外暴露服务名字

